import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Smuth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
