import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import { ResultProvider } from '../context/ResultContext'
import Footer from '@/components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CGPA Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResultProvider>
          <Navbar />
          {children}
          <Footer />
        </ResultProvider>
      </body>
    </html>
  )
}
